  select * from customer;

--What is the total revenue generated by male vs female customers?

SELECT Gender, 
       SUM([Purchase Amount (USD)]) AS revenue
FROM dbo.customer
GROUP BY Gender;

--Which customers used a discount but still spent more than
--the average purchase amount?
SELECT [Customer ID], 
       [Purchase Amount (USD)]
FROM dbo.customer
WHERE [Discount Applied] = 'Yes'
  AND [Purchase Amount (USD)] >= (
      SELECT AVG([Purchase Amount (USD)]) 
      FROM dbo.customer
  );

  -- Which are the top 5 products with the highest average
  --review rating?

SELECT TOP 5 
       [Item Purchased],
       round(AVG([Review Rating]),2) AS avg_rating
FROM dbo.customer
GROUP BY [Item Purchased]
ORDER BY avg_rating DESC;

--compare the average purchase amounts between standard and express shipping

select [Shipping Type],
avg([Purchase Amount (USD)])
from dbo.customer
where [Shipping Type] in ('Standard','Express')
group by [Shipping Type]

--do subscribes customers spend more?
--compare average spend and total revenue between subscribers and non subscribers

select [Subscription Status],
count([Customer ID]) as total_customers,
avg([Purchase Amount (USD)]) as avg_spend,
sum([Purchase Amount (USD)]) as total_revenue
from dbo.customer 
group by  [Subscription Status]
order by total_revenue, avg_spend

--which 5 products have the highest percentage 
--  of purchases with discounts applied?
select  top 5 [Item Purchased],
round(100 * sum(case when [Discount Applied]='Yes' then 1 else 0 end) / count(*),2)
as discount_rate 
from customer
group by [Item Purchased]
order by discount_rate desc;

--segment customers into new , returning and loyal based
--on their previous purchases and show the count of each segment

with customer_type as(
select [Customer ID],[Previous Purchases],
case
when [Previous Purchases]=1 then 'New'
when [Previous Purchases] between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from dbo.customer
)
select customer_segment , count(*) as 'no_of_customers'
from customer_type
group by customer_segment
order by no_of_customers desc

--what are the top 3 most purchased products within each category

with item_counts as
(
select Category,
[Item Purchased],
count([Item Purchased]) as total_orders,
row_number() over (partition by category order by count([Customer ID])desc)
as item_rank
from customer
group by Category , [Item Purchased]
)
select item_rank, Category,
[item Purchased],total_orders
from item_counts 
where item_rank<=3


--Are customers who are repeat buyers (more than previous 5 purchases) also likely to subscribe?
select [Subscription Status],
count([Customer ID]) as repeat_buyers
from dbo.customer
where [Previous Purchases]>5
group by [Subscription Status]

--what is the revenue contribution of each age ?
select [Age],
sum([Purchase Amount (USD)]) as total_revenue
from dbo.customer
group by [Age]
order by total_revenue desc